[template]
cargo_generate_version = ">=0.20.0"
ignore = ["hooks", "*.md"]

[placeholders]
project_type = { type = "string", prompt = "Choose project type?", choices = [
  "cli",
  # "tui", # TODO:
], default = "cli" }

[hooks]
init = ["hooks/ask_project.rhai"]
pre = ["hooks/template.rhai"]

[conditional.'project_type == "cli"'.placeholders]
use_tokio = { type = "bool", prompt = "With `Tokio` crate?", default = false }
